### ISSUE TITLE
Slide number progresses in expanded view

### ISSUE THREAD

**Issue by tim-tx** [monperrus/ExpandAnimations#23] opened 2018-09-05 22:49 UTC
If I put slide numbers in the footer, the number still progresses with "animations" in the expanded version. Usually it would still be considered one slide though.

**Comment by monperrus** [comment] 2018-09-06 13:30
Thanks for the suggestion. Let's hope that somebody picks this issue and gets it fixed!

**Comment by Bessonov** [comment] 2019-03-11 21:37
Duplicate of #10

**Comment by monperrus** [comment] 2019-03-12 06:34
Thanks!

**Closed by monperrus** 2019-03-12 06:34 UTC
