### ISSUE TITLE
Inadmissible value or data type

### ISSUE THREAD

**Issue by tuncK** [monperrus/ExpandAnimations#22] opened 2018-07-21 00:55 UTC
I had previously used the extension without problems, but now I have Libreoffice 6.0.  When I attempt to use the extension on slides.odp, the program starts by generating slides-expanded.odp, but later quits with error:

`Inadmissible value or data type. Index out of defined range.`

For the problem, Basic editor points to the line 208, which is:
`dim visibility(UBound(shapes), nFrames-1) as Boolean`

**Comment by georoen** [comment] 2019-01-22 10:21
Experiencing the same error here...

**Comment by monperrus** [comment] 2019-06-25 03:18
Duplicate of #8, please comment or subscribe to #8.

**Closed by monperrus** 2019-06-25 03:18 UTC
